/*
  Generates src/lib/palette.ts from the :root and .dark blocks in
  src/styles/tailwind.css.

    npm run palette

  The CSS is the source of truth — Tailwind needs literal values there to
  generate utilities, and the SCSS modules read the same custom properties. But
  the Vision UI MUI theme is plain JavaScript: it computes gradients and alpha
  blends from hex values, so it cannot read a CSS variable.

  Generating the JS mirror instead of hand-writing it is the whole point. A
  hand-kept copy drifts the first time someone edits one and not the other, and
  the symptom is subtle — a dashboard whose blues are almost, but not quite, the
  palette's blues.
*/
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const cssPath = join(here, "..", "src", "styles", "tailwind.css");
const outPath = join(here, "..", "src", "lib", "palette.ts");

const css = readFileSync(cssPath, "utf8");

/**
 * Every `--name: value;` declared by rules whose selector is exactly
 * `selector`, in source order — the palette is split across more than one
 * block (raw tokens first, derived ones after), and later wins as in CSS.
 *
 * Selectors are matched as rules at the start of a line rather than by
 * substring: `.dark` also appears inside
 * `@custom-variant dark (&:where(.dark, .dark *))`, and a plain indexOf finds
 * that first and then walks into the following `:root {` — which silently
 * yields a dark palette identical to the light one.
 */
function readBlocks(selector) {
  const rule = new RegExp(
    `^${selector.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}\\s*\\{`,
    "gm",
  );
  const out = {};
  let found = false;
  for (const match of css.matchAll(rule)) {
    found = true;
    const open = css.indexOf("{", match.index);
    let depth = 0;
    let end = open;
    for (let i = open; i < css.length; i += 1) {
      if (css[i] === "{") depth += 1;
      else if (css[i] === "}") {
        depth -= 1;
        if (depth === 0) {
          end = i;
          break;
        }
      }
    }
    for (const m of css.slice(open + 1, end).matchAll(/^\s*--([\w-]+):\s*([^;]+);/gm)) {
      out[m[1]] = m[2].trim();
    }
  }
  if (!found) throw new Error(`No ${selector} block in tailwind.css`);
  return out;
}

// Only literal colours are useful to the MUI theme. A value that is itself a
// var() or a color-mix() cannot be resolved without a browser, and the theme
// needs real hex it can do arithmetic on.
const isLiteral = (v) => /^#([0-9a-f]{3}|[0-9a-f]{6})$/i.test(v);

const root = readBlocks(":root");
const dark = { ...root, ...readBlocks(".dark") };

const light = Object.fromEntries(
  Object.entries(root).filter(([, v]) => isLiteral(v)),
);
const darkLiterals = Object.fromEntries(
  Object.entries(dark).filter(([, v]) => isLiteral(v)),
);

const keys = [...new Set([...Object.keys(light), ...Object.keys(darkLiterals)])].sort();
const missing = keys.filter((k) => !light[k] || !darkLiterals[k]);
if (missing.length) {
  console.warn(`  note: only defined in one mode -> ${missing.join(", ")}`);
}

const entries = (obj) =>
  keys
    .filter((k) => obj[k])
    .map((k) => `  "${k}": "${obj[k].toLowerCase()}",`)
    .join("\n");

const file = `// GENERATED by scripts/generate-palette.mjs — do not edit.
// Source of truth: src/styles/tailwind.css. Regenerate with \`npm run palette\`.
//
// The Vision UI MUI theme is JavaScript and computes gradients and alpha blends
// from hex values, so it cannot read the CSS custom properties directly. This
// is the same palette, in a form JS can do arithmetic on.

export type PaletteMode = "light" | "dark";

export const lightPalette = {
${entries(light)}
} as const;

export const darkPalette: Record<keyof typeof lightPalette, string> = {
${entries(darkLiterals)}
};

export type PaletteToken = keyof typeof lightPalette;

/** The palette for a mode. */
export function palette(mode: PaletteMode) {
  return mode === "dark" ? darkPalette : lightPalette;
}
`;

mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, file);
console.log(`Wrote ${outPath} — ${keys.length} tokens x 2 modes`);
