// GENERATED by scripts/generate-palette.mjs — do not edit.
// Source of truth: src/styles/tailwind.css. Regenerate with `npm run palette`.
//
// The Vision UI MUI theme is JavaScript and computes gradients and alpha blends
// from hex values, so it cannot read the CSS custom properties directly. This
// is the same palette, in a form JS can do arithmetic on.

export type PaletteMode = "light" | "dark";

export const lightPalette = {
  "accent": "#e3ecf6",
  "accent-foreground": "#1e9df1",
  "background": "#ffffff",
  "border": "#e1eaef",
  "card": "#f7f8f8",
  "card-foreground": "#0f1419",
  "chart-1": "#1e9df1",
  "chart-2": "#00b87a",
  "chart-3": "#f7b928",
  "chart-4": "#17bf63",
  "chart-5": "#e0245e",
  "chart-6": "#7856ff",
  "chart-7": "#ff7a00",
  "chart-8": "#5b7083",
  "destructive": "#f4212e",
  "destructive-foreground": "#ffffff",
  "foreground": "#0f1419",
  "input": "#f7f9fa",
  "muted": "#e5e5e6",
  "muted-foreground": "#0f1419",
  "popover": "#ffffff",
  "popover-foreground": "#0f1419",
  "primary": "#1e9df1",
  "primary-foreground": "#ffffff",
  "ring": "#1da1f2",
  "secondary": "#0f1419",
  "secondary-foreground": "#ffffff",
  "sidebar": "#f7f8f8",
  "sidebar-accent": "#e3ecf6",
  "sidebar-accent-foreground": "#1e9df1",
  "sidebar-border": "#e1e8ed",
  "sidebar-foreground": "#0f1419",
  "sidebar-primary": "#1e9df1",
  "sidebar-primary-foreground": "#ffffff",
  "sidebar-ring": "#1da1f2",
} as const;

export const darkPalette: Record<keyof typeof lightPalette, string> = {
  "accent": "#061622",
  "accent-foreground": "#1c9cf0",
  "background": "#000000",
  "border": "#242628",
  "card": "#17181c",
  "card-foreground": "#d9d9d9",
  "chart-1": "#1e9df1",
  "chart-2": "#00b87a",
  "chart-3": "#f7b928",
  "chart-4": "#17bf63",
  "chart-5": "#e0245e",
  "chart-6": "#7856ff",
  "chart-7": "#ff7a00",
  "chart-8": "#5b7083",
  "destructive": "#f4212e",
  "destructive-foreground": "#ffffff",
  "foreground": "#e7e9ea",
  "input": "#22303c",
  "muted": "#181818",
  "muted-foreground": "#72767a",
  "popover": "#000000",
  "popover-foreground": "#e7e9ea",
  "primary": "#1c9cf0",
  "primary-foreground": "#ffffff",
  "ring": "#1da1f2",
  "secondary": "#f0f3f4",
  "secondary-foreground": "#0f1419",
  "sidebar": "#17181c",
  "sidebar-accent": "#061622",
  "sidebar-accent-foreground": "#1c9cf0",
  "sidebar-border": "#38444d",
  "sidebar-foreground": "#d9d9d9",
  "sidebar-primary": "#1da1f2",
  "sidebar-primary-foreground": "#ffffff",
  "sidebar-ring": "#1da1f2",
};

export type PaletteToken = keyof typeof lightPalette;

/** The palette for a mode. */
export function palette(mode: PaletteMode) {
  return mode === "dark" ? darkPalette : lightPalette;
}
