/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Signup
         * @description Create an account and sign in immediately.
         *
         *     No email verification step: nothing here is sent by email, and a
         *     verification flow on a local, on-premise system would add a mail server to
         *     the deployment for no security the deployment actually gains.
         */
        post: operations["signup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Exchange an email and password for a token pair.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reset Password
         * @description Set a new password directly from an email address — demo shortcut.
         *
         *     No emailed token, no proof the requester owns the inbox: whoever submits an
         *     email gets to set that account's password. Fine for a local demo where
         *     nobody else can reach this API; the moment this is reachable by anyone but
         *     the account holder, this needs a time-limited emailed token in front of it.
         *
         *     The response is identical whether or not the email has an account, for the
         *     same reason the module docstring gives for login: a reset endpoint that
         *     answers differently for known/unknown emails is an account-enumeration
         *     oracle.
         */
        post: operations["reset_password"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh
         * @description Trade a refresh token for a new pair.
         *
         *     Both tokens are reissued, so a session that stays active never has to log in
         *     again, while an abandoned one expires on the refresh token's clock.
         */
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Me
         * @description The signed-in user. The frontend's route guard calls this on load.
         */
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Profile
         * @description This user's preferences. Empty defaults when they have not answered yet.
         */
        get: operations["get_profile"];
        /**
         * Put Profile
         * @description Write the profile. A partial body updates only the fields it carries.
         *
         *     PUT rather than PATCH is a small lie about semantics, and a deliberate one:
         *     the interview arrives in pieces as the agent asks questions, and requiring
         *     the client to send the whole profile every time would mean a dropped answer
         *     silently erases an earlier one.
         */
        put: operations["put_profile"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/views": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Views
         * @description Every dashboard this user kept, newest first.
         */
        get: operations["list_views"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/views/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Put View
         * @description Create or replace a saved dashboard.
         *
         *     Component types are not checked against a catalog here. The catalog lives in
         *     the frontend, and duplicating it in Python would guarantee the two drift;
         *     an unknown type renders as a visible placeholder tile instead -- which
         *     matters, because the AI Overview page writes this JSON and a model will
         *     eventually name a component that does not exist.
         */
        put: operations["put_view"];
        post?: never;
        /** Delete View */
        delete: operations["delete_view"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/banks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * All Banks
         * @description Every bank, what it publishes, and what is currently in maintenance.
         *
         *     All ten are listed, including the two with no callable endpoint. A bank that
         *     publishes nothing is a legitimate answer with a reason in `notes`, not an
         *     omission.
         */
        get: operations["all_banks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/banks/families": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Product Families
         * @description The product families that make two banks comparable.
         *
         *     Declared ahead of /{bank} so the literal path wins the match -- otherwise
         *     "families" is read as a bank name and every request 404s.
         */
        get: operations["product_families"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/banks/{bank}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One Bank */
        get: operations["one_bank"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/banks/{bank}/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Bank Products
         * @description A bank's own catalogue, as the bank publishes it.
         */
        get: operations["bank_products"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/banks/{bank}/finance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Bank Finance Quote
         * @description A live financing quote, including the full payment schedule.
         *
         *     The number is the bank's own. Nothing here recomputes an installment or
         *     fills a gap with a formula -- an endpoint that will not answer is reported
         *     as not answering.
         */
        get: operations["bank_finance_quote"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/banks/{bank}/profit-share": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Bank Profit Share Quote
         * @description A live participation-account quote.
         *
         *     Banks disagree about whether a product takes a term in days or months, so
         *     the response repeats the unit that actually answered rather than echoing
         *     the one that was asked for.
         */
        get: operations["bank_profit_share_quote"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/banks/{bank}/rates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Bank Rates
         * @description A bank's FX and gold table, with the timestamp it was quoted at.
         *
         *     Cached for a few seconds, and only here. The board is a live page: it polls,
         *     and without this every tab refreshing would be its own request to the bank.
         *     Two of these boards are page reads and one bank fingerprints TLS, so the
         *     browser polls freely and the banks see one request per TTL.
         */
        get: operations["bank_rates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/banks/{bank}/card": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Bank Card Quote
         * @description An instalment plan for a credit-card purchase.
         *
         *     Only two banks publish this (Kuveyt Türk, Vakıf). Kuveyt Türk's own card
         *     catalogue has a duplicate code -- `BP` names two different cards -- so a
         *     caller quoting `BP` gets whichever the catalogue lists first; this is a
         *     known gap in the bank's own data, not something resolved here.
         */
        get: operations["bank_card_quote"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/banks/{bank}/miles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Bank Mile Rates
         * @description Miles earned per lira, by card, tier and spending category.
         *
         *     Kuveyt Türk is the only publisher, and its table is 567 rows -- every
         *     combination of card, membership tier and category. Filtering by card or
         *     category happens in the frontend rather than as query parameters here,
         *     which would need their own "list the valid values" endpoints to be usable.
         */
        get: operations["bank_mile_rates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/compare/finance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Compare Finance
         * @description One financing product at every bank that sells it.
         *
         *     Payment schedules are omitted -- ten full schedules would be megabytes of
         *     rows nobody reads in a ranking. Fetch one from /api/banks/{bank}/finance.
         */
        get: operations["compare_finance"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/compare/profit-share": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Compare Profit Share
         * @description One participation account at every bank that sells it.
         */
        get: operations["compare_profit_share"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/compare/exchange": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Compare Exchange
         * @description The same conversion at every bank that converts.
         *
         *     Each result carries `derived`. False means the bank converted it itself;
         *     True means we multiplied the bank's own quoted rate, which is the single
         *     agreed exception to "never compute a number ourselves". The UI must label
         *     a derived figure -- it is our arithmetic, not the bank's answer.
         */
        get: operations["compare_exchange"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/compare/card": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Compare Card
         * @description Every card at every bank that publishes a card calculator, ranked.
         *
         *     Cards have no cross-bank family: each bank sells its own catalogue under
         *     its own names, so this quotes every card every in-scope bank publishes
         *     rather than one named product. A bank that states only a rate and no
         *     instalment sinks to the bottom of the ranking rather than winning it.
         */
        get: operations["compare_card"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/compare/constraints": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Compare Constraints
         * @description What the selected banks will accept, before anyone is asked.
         *
         *     Read from the catalogues, which the provider layer caches, so a form can
         *     call this on every change without touching a bank endpoint each time.
         *
         *     The value is `intersection`: Dünya's konut product stops at 84 months while
         *     the other five reach 120, so a run including Dünya can only ask for 84.
         *     Showing that as a ceiling -- with the bank that set it -- beats letting
         *     someone submit 360 and watch every bank decline.
         */
        get: operations["compare_constraints"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/components": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * All Categories
         * @description Every topic page, and whether a producer has filled it yet.
         */
        get: operations["all_categories"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/components/{category}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Category Components
         * @description The ordered components for one topic page.
         *
         *     An unknown category 404s naming the valid ones. A known category with no
         *     fixture answers 200 with an empty list: "this page has no content yet" is
         *     an answer, not a failure, and the UI has a state for it.
         */
        get: operations["category_components"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/compare-tables": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Tables
         * @description Every table in one category, for the browse-by-subcategory picker.
         */
        get: operations["list_tables"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/compare-tables/{table_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Table
         * @description One table, shaped for `<TableWidget />` -- a 'Banka' column first (bank
         *     keys the frontend already knows how to render), then every column the
         *     table itself declared, in the order the producer chose.
         */
        get: operations["get_table"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search Corpus
         * @description The passages most relevant to the query, each with an openable citation.
         */
        get: operations["search_corpus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Sessions
         * @description This user's conversations, most recent first.
         */
        get: operations["list_sessions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Chat Session
         * @description One conversation with all of its turns.
         */
        get: operations["get_chat_session"];
        put?: never;
        post?: never;
        /** Delete Chat Session */
        delete: operations["delete_chat_session"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ask
         * @description Ask a question. Returns an SSE stream of `StreamEvent` frames.
         *
         *     `response_model=StreamEvent` is a documentation device -- the endpoint
         *     returns a stream, not that object. Declaring it is what puts the frame shape
         *     into the OpenAPI schema, so the frontend's event types are generated like
         *     everything else instead of being the one hand-written surface in the app.
         */
        post: operations["ask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness. Answers as long as the process is up.
         */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ready
         * @description Readiness: every dependency checked, and every failure named.
         *
         *     All dependencies are probed even after the first failure. A report saying
         *     only "Postgres is down" when Qdrant is down too costs a second deploy to
         *     discover the second problem.
         */
        get: operations["ready"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AskRequest
         * @description A question. `session_id` omitted starts a new conversation.
         */
        AskRequest: {
            /** Question */
            question: string;
            /** Session Id */
            session_id?: string | null;
        };
        /**
         * BankLimitsOut
         * @description What one bank will accept for a family, read from its own catalogue.
         */
        BankLimitsOut: {
            /** Bank */
            bank: string;
            /**
             * Product
             * @description The product, or the family stem when the bank bands it.
             */
            product: string;
            /**
             * Products Matched
             * @description Above 1 the bank splits this into term/amount bands and picks one at quote time; the range below is the envelope of all of them.
             * @default 1
             */
            products_matched: number;
            /** Min Amount */
            min_amount?: number | null;
            /** Max Amount */
            max_amount?: number | null;
            /** Min Term */
            min_term?: number | null;
            /** Max Term */
            max_term?: number | null;
            /** Currencies */
            currencies?: string[];
        };
        /**
         * BankOut
         * @description One bank, what it publishes, and what is currently down.
         *
         *     `publishes` and `maintenance` are different absences and are reported
         *     separately: a bank that does not sell car finance and a bank whose car
         *     finance endpoint is broken this morning must never look alike in the UI.
         */
        BankOut: {
            /**
             * Name
             * @description The key every other endpoint takes.
             */
            name: string;
            /** Display Name */
            display_name: string;
            /** Publishes */
            publishes: string[];
            /**
             * Maintenance
             * @description Capabilities the last health check found failing.
             */
            maintenance?: string[];
            /**
             * Notes
             * @default
             */
            notes: string;
        };
        /** CardInstallmentQuoteOut */
        CardInstallmentQuoteOut: {
            /** Bank */
            bank: string;
            card: components["schemas"]["ProductOut"];
            /** Amount */
            amount: number;
            /** Installments */
            installments: number;
            /**
             * Installment
             * @description Monthly payment, or null where the bank publishes only a rate.
             */
            installment?: number | null;
            /** Total */
            total?: number | null;
            /** Profit Rate */
            profit_rate: number;
            /**
             * Derived
             * @default false
             */
            derived: boolean;
        };
        /**
         * CategoryOut
         * @description One topic page, and whether a producer has filled it yet.
         */
        CategoryOut: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Has Components */
            has_components: boolean;
        };
        /** ChatMessageOut */
        ChatMessageOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Role
             * @enum {string}
             */
            role: "user" | "assistant";
            /** Content */
            content: string;
            /** Citations */
            citations?: components["schemas"]["ChunkOut"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ChatSessionDetail */
        ChatSessionDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Messages */
            messages?: components["schemas"]["ChatMessageOut"][];
        };
        /** ChatSessionOut */
        ChatSessionOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * ChunkOut
         * @description One retrieved passage, with the link that proves it.
         */
        ChunkOut: {
            /** Score */
            score: number;
            /**
             * Cite Url
             * @description Openable: page#anchor, or form.pdf#page=7.
             */
            cite_url: string;
            /** Text */
            text: string;
            /**
             * Bank
             * @default
             */
            bank: string;
            /**
             * Title
             * @default
             */
            title: string;
            /**
             * Doc Kind
             * @default
             */
            doc_kind: string;
            /**
             * Source Type
             * @default
             */
            source_type: string;
            /** Campaign End */
            campaign_end?: string | null;
            /**
             * From Vision
             * @description Read by OCR from a scanned page. The UI should mark it, and the agent should hedge on exact figures taken from it.
             * @default false
             */
            from_vision: boolean;
        };
        /** ColumnOut */
        ColumnOut: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Type */
            type?: string | null;
        };
        /** ComparisonOut */
        ComparisonOut: {
            /** Category */
            category: string;
            /** Family */
            family: string;
            /** Quotes */
            quotes?: components["schemas"]["FinanceQuoteOut"][];
            /** Profit Share Quotes */
            profit_share_quotes?: components["schemas"]["ProfitShareQuoteOut"][];
            /** Conversions */
            conversions?: components["schemas"]["ConversionOut"][];
            /** Card Quotes */
            card_quotes?: components["schemas"]["CardInstallmentQuoteOut"][];
            /** Unavailable */
            unavailable?: components["schemas"]["UnavailableOut"][];
            /**
             * Seconds
             * @description How long the fan-out took.
             */
            seconds: number;
        };
        /**
         * Component
         * @description One tile on a dashboard.
         *
         *     `type` names a component in the frontend catalog; `props` is whatever that
         *     component takes. Unvalidated on purpose -- the catalog lives in TypeScript,
         *     and duplicating each component's prop schema in Python would guarantee the
         *     two drift. The frontend renders an unknown type as a visible placeholder.
         */
        Component: {
            /** Type */
            type: string;
            /** Props */
            props?: {
                [key: string]: unknown;
            };
        };
        /**
         * ComponentsResponse
         * @description Everything a topic page needs to render, in one response.
         *
         *     `components` is ordered, and the order is meaningful -- it is the producer's
         *     argument, not an arbitrary set. The frontend preserves it and computes
         *     widths itself.
         */
        ComponentsResponse: {
            /**
             * Category
             * @description A key from GET /api/components.
             */
            category: string;
            /**
             * Generated At
             * @description When the producer built these, ISO-8601. Empty if unknown.
             * @default
             */
            generated_at: string;
            /**
             * Source
             * @description fixture | agent. Until the RAG agent lands these are hand-written development fixtures; the UI marks them so nobody reads placeholder content as bank data.
             * @default fixture
             */
            source: string;
            /** Components */
            components?: components["schemas"]["Component"][];
        };
        /** ConstraintsOut */
        ConstraintsOut: {
            /** Category */
            category: string;
            /** Family */
            family: string;
            /** Banks */
            banks?: components["schemas"]["BankLimitsOut"][];
            /** Unavailable */
            unavailable?: components["schemas"]["UnavailableOut"][];
            intersection: components["schemas"]["IntersectionOut"];
        };
        /** ConversionOut */
        ConversionOut: {
            /** Bank */
            bank: string;
            /** Source */
            source: string;
            /** Target */
            target: string;
            /** Amount */
            amount: string;
            /** Result */
            result: string;
            /** Rate */
            rate: string;
            /**
             * Derived
             * @description True when we multiplied a quoted rate rather than the bank converting server-side. The UI must label these.
             */
            derived: boolean;
        };
        /** DependencyOut */
        DependencyOut: {
            /** Name */
            name: string;
            /** Ok */
            ok: boolean;
            /**
             * Detail
             * @default
             */
            detail: string;
        };
        /**
         * FamilyOut
         * @description A product family -- the thing that makes two banks comparable.
         */
        FamilyOut: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /**
             * Category
             * @description finance | profit_share
             */
            category: string;
            /**
             * Banks
             * @description Banks that sell it.
             */
            banks: string[];
        };
        /** FinanceQuoteOut */
        FinanceQuoteOut: {
            /** Bank */
            bank: string;
            product: components["schemas"]["ProductOut"];
            /** Amount */
            amount: number;
            /** Term */
            term: number;
            /**
             * Installment
             * @description Monthly payment, or null where the bank publishes only a rate.
             */
            installment?: number | null;
            /** Total */
            total?: number | null;
            /** Profit Rate */
            profit_rate: number;
            /** Annual Cost Rate */
            annual_cost_rate?: number | null;
            /** Fees */
            fees?: {
                [key: string]: number;
            };
            /**
             * Variant
             * @description e.g. "sigortali" / "sigortasiz". Empty where the bank does not split.
             * @default
             */
            variant: string;
            /**
             * General
             * @default false
             */
            general: boolean;
            /**
             * Derived
             * @default false
             */
            derived: boolean;
            /** Schedule */
            schedule?: components["schemas"]["PaymentRowOut"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthOut */
        HealthOut: {
            /**
             * Status
             * @default ok
             */
            status: string;
            /** Environment */
            environment: string;
        };
        /**
         * IntersectionOut
         * @description The range every bank in the run will accept.
         *
         *     `limited_by` names the bank behind each bound, and only when one bank is
         *     actually the reason -- a bound every bank shares is the product's shape, not
         *     somebody's restriction.
         */
        IntersectionOut: {
            /** Min Amount */
            min_amount?: number | null;
            /** Max Amount */
            max_amount?: number | null;
            /** Min Term */
            min_term?: number | null;
            /** Max Term */
            max_term?: number | null;
            /** Currencies */
            currencies?: string[];
            /** Limited By */
            limited_by?: {
                [key: string]: string[];
            };
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * MileRateOut
         * @description One reward rate: miles earned per lira, for one card/tier/category.
         *
         *     Kuveyt Türk's table is 567 rows -- card x tier x category -- so the
         *     frontend filters this client-side rather than the route taking three query
         *     parameters that would each need their own "list the valid ones" endpoint.
         */
        MileRateOut: {
            /** Card */
            card: string;
            /** Tier */
            tier: string;
            /** Category */
            category: string;
            /** Per Lira */
            per_lira: number;
        };
        /** PaymentRowOut */
        PaymentRowOut: {
            /** Order */
            order: number;
            /** Amount */
            amount: number;
            /** Principal */
            principal: number;
            /** Profit */
            profit: number;
            /** Taxes */
            taxes: number;
            /** Remaining */
            remaining: number;
            /**
             * Due Date
             * @default
             */
            due_date: string;
        };
        /** ProductOut */
        ProductOut: {
            /** Code */
            code: string;
            /** Name */
            name: string;
            /** Category */
            category: string;
            /** Min Amount */
            min_amount?: number | null;
            /** Max Amount */
            max_amount?: number | null;
            /** Min Term */
            min_term?: number | null;
            /** Max Term */
            max_term?: number | null;
            /** Currencies */
            currencies?: string[];
            /** Rate */
            rate?: number | null;
        };
        /**
         * ProfileIn
         * @description A profile write. Every field optional -- a partial answer is a valid answer.
         *
         *     Bank and family keys are validated against `banks.list_banks()` and
         *     `banks.families` in the router, not here: pydantic would have to import the
         *     bank layer to know them, and the error is more useful when it can name what
         *     is available.
         */
        ProfileIn: {
            /** Persona */
            persona?: string | null;
            /** Banks */
            banks?: string[] | null;
            /** Families */
            families?: string[] | null;
            /** Typical Amount */
            typical_amount?: number | null;
            /** Typical Term Months */
            typical_term_months?: number | null;
            /** Answers */
            answers?: {
                [key: string]: unknown;
            } | null;
        };
        /** ProfileOut */
        ProfileOut: {
            /** Persona */
            persona: string;
            /** Banks */
            banks: string[];
            /** Families */
            families: string[];
            /** Typical Amount */
            typical_amount: number | null;
            /** Typical Term Months */
            typical_term_months: number | null;
            /** Answers */
            answers: {
                [key: string]: unknown;
            };
            /** Completed At */
            completed_at: string | null;
        };
        /** ProfitShareQuoteOut */
        ProfitShareQuoteOut: {
            /** Bank */
            bank: string;
            product: components["schemas"]["ProductOut"];
            /** Amount */
            amount: number;
            /** Term */
            term: number;
            /** Currency */
            currency: string;
            /** Term Unit */
            term_unit: string;
            /** Ratio */
            ratio?: number | null;
            /** Gross Profit */
            gross_profit: number;
            /** Net Profit */
            net_profit: number;
            /** Gross Annual Rate */
            gross_annual_rate?: number | null;
            /** Net Annual Rate */
            net_annual_rate?: number | null;
            /**
             * Variant
             * @default
             */
            variant: string;
            /**
             * General
             * @default false
             */
            general: boolean;
        };
        /** RateOut */
        RateOut: {
            /** Code */
            code: string;
            /** Name */
            name: string;
            /** Buy */
            buy: number;
            /** Sell */
            sell: number;
            /**
             * Unit
             * @default 1
             */
            unit: string;
            /**
             * As Of
             * @default
             */
            as_of: string;
            /**
             * Derived
             * @description True when the pair was worked out from the bank's own converter rather than read off a published feed. The UI must label these: the numbers are the bank's, the inversion is ours.
             * @default false
             */
            derived: boolean;
            /**
             * Canonical
             * @description The shared symbol for this instrument -- XAU for gold whether the bank calls it XAU or 'ALT (gr)'. Cross-bank grouping keys on (canonical, unit); without it the frontend would have to duplicate the alias table and drift when a bank renames a code.
             * @default
             */
            canonical: string;
        };
        /** ReadyOut */
        ReadyOut: {
            /**
             * Ready
             * @description False if any dependency is down.
             */
            ready: boolean;
            /** Dependencies */
            dependencies: components["schemas"]["DependencyOut"][];
        };
        /** RefreshRequest */
        RefreshRequest: {
            /** Refresh Token */
            refresh_token: string;
        };
        /** ResetPasswordRequest */
        ResetPasswordRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** New Password */
            new_password: string;
        };
        /** ResetPasswordResponse */
        ResetPasswordResponse: {
            /** Detail */
            detail: string;
        };
        /** RowOut */
        RowOut: {
            /** Cells */
            cells: {
                [key: string]: string | number | boolean | null;
            };
            /** Cite Url */
            cite_url?: string | null;
            /**
             * Cite Note
             * @description The pipeline's own note on why this source supports the row — shown as a hover title on the citation link, not a second dashboard.
             */
            cite_note?: string | null;
        };
        /** SavedViewIn */
        SavedViewIn: {
            /** Slug */
            slug: string;
            /** Title */
            title: string;
            /** Components */
            components?: components["schemas"]["Component"][];
            /**
             * Generated
             * @default false
             */
            generated: boolean;
        };
        /** SavedViewOut */
        SavedViewOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Slug */
            slug: string;
            /** Title */
            title: string;
            /** Components */
            components: components["schemas"]["Component"][];
            /** Generated */
            generated: boolean;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** SearchResponse */
        SearchResponse: {
            /** Query */
            query: string;
            /** Active Only */
            active_only: boolean;
            /** Hits */
            hits: components["schemas"]["ChunkOut"][];
        };
        /** SignupRequest */
        SignupRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /**
             * Display Name
             * @default
             */
            display_name: string;
            /**
             * Locale
             * @default tr
             */
            locale: string;
        };
        /**
         * StreamEvent
         * @description One SSE frame. Only the fields belonging to `type` are populated.
         *
         *     Declared as a response model on the streaming endpoint purely so it lands in
         *     the OpenAPI schema; the endpoint returns a stream, not this object.
         */
        StreamEvent: {
            /**
             * Type
             * @enum {string}
             */
            type: "status" | "token" | "citation" | "done" | "error";
            /**
             * Stage
             * @description status only: retrieving | pricing | writing.
             */
            stage?: string | null;
            /**
             * Text
             * @description token only.
             */
            text?: string | null;
            /** @description citation only. */
            citation?: components["schemas"]["ChunkOut"] | null;
            /**
             * Message Id
             * @description done only.
             */
            message_id?: string | null;
            /**
             * Session Id
             * @description done only.
             */
            session_id?: string | null;
            /**
             * Detail
             * @description error only.
             */
            detail?: string | null;
        };
        /**
         * TableDetailOut
         * @description Shaped exactly like the frontend's `TableProps` (`UI/src/lib/contract.ts`)
         *     so it can be spread straight into `<TableWidget />` with no translation
         *     layer on the client.
         */
        TableDetailOut: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /**
             * Subtitle
             * @default
             */
            subtitle: string;
            /**
             * Notes
             * @default
             */
            notes: string;
            /** Columns */
            columns: components["schemas"]["ColumnOut"][];
            /** Rows */
            rows: components["schemas"]["RowOut"][];
        };
        /**
         * TableListOut
         * @description Every table in one category, plus the subcategories present in it.
         *
         *     `subcategories` is derived from the tables actually returned, not the
         *     global registry — a category-scoped dropdown should never offer a
         *     subcategory that has zero tables under this category.
         */
        TableListOut: {
            /** Category */
            category: string;
            /** Subcategories */
            subcategories: string[];
            /** Tables */
            tables: components["schemas"]["TableSummaryOut"][];
        };
        /**
         * TableSummaryOut
         * @description One table, without its rows — enough to list and pick from.
         */
        TableSummaryOut: {
            /** Id */
            id: string;
            /** Topic */
            topic: string;
            /** Docstring */
            docstring: string;
            /**
             * Category
             * @description 'ürün' or 'kampanya'.
             */
            category: string;
            /** Subcategory */
            subcategory: string;
        };
        /**
         * TokenPair
         * @description What a successful signup, login or refresh returns.
         */
        TokenPair: {
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            /**
             * Expires In
             * @description Access token lifetime, in seconds.
             */
            expires_in: number;
        };
        /**
         * UnavailableOut
         * @description A bank absent from a ranking, and why.
         *
         *     `why` is one of not_offered | maintenance | declined | error. Four distinct
         *     states, kept distinct: "no bank offers this" and "we could not reach anyone"
         *     are opposite answers.
         */
        UnavailableOut: {
            /** Bank */
            bank: string;
            /** Why */
            why: string;
            /**
             * Detail
             * @default
             */
            detail: string;
        };
        /** UserOut */
        UserOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email */
            email: string;
            /** Display Name */
            display_name: string;
            /** Locale */
            locale: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Has Profile
             * @default false
             */
            has_profile: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    signup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignupRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_password: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResetPasswordResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
        };
    };
    get_profile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileOut"];
                };
            };
        };
    };
    put_profile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_views: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedViewOut"][];
                };
            };
        };
    };
    put_view: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SavedViewIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedViewOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_view: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    all_banks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BankOut"][];
                };
            };
        };
    };
    product_families: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FamilyOut"][];
                };
            };
        };
    };
    one_bank: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A bank key from GET /api/banks. */
                bank: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BankOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bank_products: {
        parameters: {
            query?: {
                /** @description finance | profit_share */
                category?: string;
            };
            header?: never;
            path: {
                /** @description A bank key from GET /api/banks. */
                bank: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bank_finance_quote: {
        parameters: {
            query: {
                /** @description A product code from /products. */
                product: string;
                amount: number;
                /** @description Months. */
                term: number;
            };
            header?: never;
            path: {
                /** @description A bank key from GET /api/banks. */
                bank: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FinanceQuoteOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bank_profit_share_quote: {
        parameters: {
            query: {
                product: string;
                amount: number;
                term: number;
                unit?: string;
                currency?: string;
            };
            header?: never;
            path: {
                /** @description A bank key from GET /api/banks. */
                bank: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfitShareQuoteOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bank_rates: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A bank key from GET /api/banks. */
                bank: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RateOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bank_card_quote: {
        parameters: {
            query: {
                /** @description A card code from GET /{bank}/products?category=card. */
                card: string;
                amount: number;
                installments: number;
            };
            header?: never;
            path: {
                /** @description A bank key from GET /api/banks. */
                bank: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardInstallmentQuoteOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bank_mile_rates: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A bank key from GET /api/banks. */
                bank: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MileRateOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compare_finance: {
        parameters: {
            query: {
                /** @description A family key from /api/banks/families. */
                family: string;
                amount: number;
                /** @description Months. */
                term: number;
                /** @description Limit to these banks. Omitted, every bank that sells it is asked. */
                banks?: string[] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComparisonOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compare_profit_share: {
        parameters: {
            query: {
                family?: string;
                amount: number;
                term: number;
                unit?: string;
                currency?: string;
                /** @description Limit to these banks. Omitted, every bank that sells it is asked. */
                banks?: string[] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComparisonOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compare_exchange: {
        parameters: {
            query: {
                source: string;
                target: string;
                amount: number;
                /** @description Limit to these banks. Omitted, every bank that sells it is asked. */
                banks?: string[] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComparisonOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compare_card: {
        parameters: {
            query: {
                amount: number;
                installments: number;
                /** @description Limit to these banks. Omitted, every bank that sells it is asked. */
                banks?: string[] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComparisonOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compare_constraints: {
        parameters: {
            query: {
                /** @description A family key from GET /api/banks/families. */
                family: string;
                category?: string;
                /** @description Limit to these banks. Omitted, every bank that sells it is asked. */
                banks?: string[] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConstraintsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    all_categories: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryOut"][];
                };
            };
        };
    };
    category_components: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A key from GET /api/components. */
                category: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComponentsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tables: {
        parameters: {
            query: {
                /** @description 'ürün' or 'kampanya'. */
                category: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TableListOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_table: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description An id from GET /api/compare-tables. */
                table_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TableDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_corpus: {
        parameters: {
            query: {
                q: string;
                bank?: string | null;
                /** @description campaign | product | fee | ... */
                doc_kind?: string | null;
                /** @description web | pdf. Omitted searches both together -- the point of the single collection. Set it only to narrow. */
                source_type?: string | null;
                /** @description retail | corporate */
                audience?: string | null;
                /** @description Hide expired campaigns. Leave on. */
                active_only?: boolean;
                k?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatSessionOut"][];
                };
            };
        };
    };
    get_chat_session: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatSessionDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_chat_session: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ask: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StreamEvent"];
                    "text/event-stream": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
    ready: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyOut"];
                };
            };
        };
    };
}
